// String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.

package hashtable;

public class Difference {
    public char findTheDifference(String s, String t) {
        int sum1 = 0;
        int sum2 = 0;
        for(int i =0; i<s.length(); i++){
            sum1 = sum1 + s.charAt(i);
        }
        for(int i = 0; i<t.length(); i++){
            sum2 = sum2 + t.charAt(i);
        }
        return (char)(sum2-sum1);
    }
    public static void main(String[] args) {
        String s1 = "abcd";
        String s2 = "abcde";
        Difference d = new Difference();
        System.out.println(d.findTheDifference(s1, s2));
    }
}
